### ISSUE TITLE
Hi, I don't see option of choose file to import, either I am doing something wrong, or it doesn't support version 2.93

### ISSUE THREAD

**Issue by BhasmaSur** [iCEE-HAM/io_import_lipSync-blender2.8#3]

**Comment by Hunanbean** [comment]
It does not currently work properly with 2.9. Hence my open issue right under yours that is requesting an update.

**Comment by Hunanbean** [comment]
I managed to update it. [Here is 2.93 version](https://github.com/Hunanbean/Papagayo-NGLipsyncImporterForBlender)

**Comment by Sobollion** [comment]
Thx for update to 2.93!

**Comment by art7pro** [comment]
> I managed to update it. [Here is 2.93 version](https://github.com/Hunanbean/Papagayo-NGLipsyncImporterForBlender)

Hello. What about 3.0? When I press _Plot keys to the timeline_ I got this error.

```
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_lipSync_Importer_2_93.py", line 444, in execute
    if scn.fpath!='': lipsyncer()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_lipSync_Importer_2_93.py", line 383, in lipsyncer
    createShapekey(key.name, frame)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_import_lipSync_Importer_2_93.py", line 412, in createShapekey
    objSK.key_blocks[phoneme].keyframe_insert("value",
TypeError: bpy_struct.keyframe_insert()() takes at most 1 positional argument (4 given)

location: <unknown location>:-1

```

**Comment by Hunanbean** [comment]
Just so it is noted here too, the 3.0 update is now live over with the 2.93 update
